# Generated by Django 3.2 on 2021-04-14 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='rok_wydania',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
